### PR TITLE
Correct sync list, add issue repo and version info

### PR DESCRIPTION
**Pull request by gridhead**
Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>

### CODE REVIEW

**Review by abompard — DISMISSED** [review]

**Comment by gridhead** [comment]
Assuming it didn't find `git` (ref. https://github.com/fedora-infra/fedora-messaging/runs/6452182270?check_suite_focus=true#step:4:12), I added a directive to explicitly install it (ref. https://github.com/fedora-infra/fedora-messaging/pull/263/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R31). Let us see if it works.

**Comment by gridhead** [comment]
Hmm. This is strange. I have git installed and I can confirm that I am in the correct directory (ref. https://github.com/fedora-infra/fedora-messaging/runs/6463365423?check_suite_focus=true). It still does not seem to work.

**Comment by gridhead** [comment]
This is where I took reference from https://github.com/pre-commit/pre-commit/issues/456. I will go out there and take a walk before I have at this (again).

**Comment by abompard** [comment]
Did you have a look at the pre-commit error log? I suspect it may be related to the git safe-directory feature I fixed in FASJSON: https://github.com/fedora-infra/fasjson/commit/8f13c92964d5ba70a14477a3844b11f72f5e80c6.
I'll see if I can apply the same fix here.

**Comment by gridhead** [comment]
I tried to add a task to `cat` the logs after the job failed but then I remember that nothing really executes once a command exits out with a non-zero exit code. So it didn't quite work.

**Comment by abompard** [comment]
Well, it's more complex than I thought, so it'll have to wait for tomorrow if you don't mind (I'm supposed to be off today ;-) ).

**Comment by gridhead** [comment]
@abompard, apologies. I am totally okay with waiting on this. I will probably bang my head on Noggin in the meanwhile. :P

**Comment by abompard** [comment]
Alright, please rebase, it should pass now.

**Review by abompard — APPROVED** [review]

**Pull request merged**
