### PR TITLE
Add SECURITY.md for project security policy

### LINKED ISSUE #314: Security policy question
👋 Hello Everyone,

I'm Khaled Achech a passionate developer but I would like to start contributing more to open-source projects. This could be my first time contributing to an open-source project. I've noticed in security tab that there is no security policy for this repository and I was wondering if it's okay for me to add one as my first contribution to the project ?

### PR DESCRIPTION
**Pull request by KhaledAchech**
### Added a new security policy to the repository.

This pull request introduces a comprehensive security policy (`SECURITY.md`) to enhance the overall security posture of the project. The security policy outlines guidelines, procedures, and reporting mechanisms to address and respond to potential security vulnerabilities.

I've carefully followed the contributing guidelines, but if there are any adjustments or additional steps needed, please let me know. I appreciate your time and consideration.

### CODE REVIEW

**Review by abompard — APPROVED** [review]
Thanks!

**Comment by abompard** [comment]
Could you please rebase, amend and force-push your commit? I've added a pre-commit check that will fix some formatting in the files.

**Comment by KhaledAchech** [comment]
> Could you please rebase, amend and force-push your commit? I've added a pre-commit check that will fix some formatting in the files.

Yes, definitely. That's awesome, can you share how to setup such tests that automatically fixes files formatting and if it's applicable share any learning resources for implementing integration tests ?

**Comment by abompard** [comment]
> That's awesome, can you share how to setup such tests that automatically fixes files formatting and if it's applicable share any learning resources for implementing integration tests ?

Yes of course, we're using [pre-commit](https://pre-commit.com/), and the `.pre-commit-config.yaml` file in the repo lists the tests that will be run before each commit. You can enable it in your clone by installing pre-commit (it's probably already available in your distribution) and running `pre-commit install`.

**Comment by abompard** [comment]
In your case that would mean running `git commit --amend` after the `pre-commit install` step, so that pre-commit is triggerred on the existing content.

**Comment by KhaledAchech** [comment]
> In your case that would mean running `git commit --amend` after the `pre-commit install` step, so that pre-commit is triggerred on the existing content.

I understand, thanks for clearing that up :) I will make sure to get to it in the evening.

**Comment by KhaledAchech** [comment]
I apologize for the inconvenience before.
I think now, things should be in order :) I cleaned my commits with a rebase and followed the pre-commit installation and then I executed the amend after that I executed the force push. Hopefully now everything in order, if not please let me know what needs to be changed and also thanks for your help and patience ^^

Edit: In my previous change I forgot to fix the actual problem which is the EOF in security.md && PR314.doc. Again, I'm sorry, I got a bit too hasty and distracted.

**Comment by abompard** [comment]
Thanks @KhaledAchech !

**Comment by KhaledAchech** [comment]
> Thanks @KhaledAchech !

Awesome! Thank you for all the help ^^

**Pull request merged**
