### PR TITLE
Use tomllib from the standard library on Python 3.11

### PR DESCRIPTION
**Pull request by hroncok**
The code would be slightly easier if we fell back to tomli, but I kept using toml as this code also targets EL 8.

See https://fedoraproject.org/wiki/Changes/DeprecatePythonToml

### CODE REVIEW

**Comment by hroncok** [comment]
FTR tomli is being added to epel8, so this could be made a bit simpler.

**Comment by hroncok** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-5e36342ad8

**Comment by abompard** [comment]
OK, do you want to rework it Miro?

**Comment by hroncok** [comment]
Done.

**Comment by hroncok** [comment]
The mocks got unhappy, trying to fix that.

**Comment by hroncok** [comment]
TOMLDecodeError does not seem to have line numbers. Is that a problem?

**Comment by hroncok** [comment]
This turned out to be more tedious than I anticipated. The tests are very unforgiving to slight implementation changes :(

Anyway, I think I cracked it and

    $ tox -e=py3{6,7,8,9,10,11}-unittest

Passes.

Let me know if I shall squash or if you'd rather squash when merging. I'd like you to see my train of thought when reviewing it, so not squashing yet.

**Comment by abompard** [comment]
> Let me know if I shall squash or if you'd rather squash when merging. I'd like you to see my train of thought when reviewing it, so not squashing yet.

Yeah, got it, thanks. Please squash. Sorry it ended up more painful that it should have been.

**Comment by hroncok** [comment]
Squashed, signed off.

**Pull request merged**
