### PR TITLE
Add missing ‹requests› dependency to pyproject.toml

### PR DESCRIPTION
**Pull request by mfocko**
Related to #364
Related to packit/agile#552

### CODE REVIEW

**Review by jeremycline — DISMISSED** [review]
FWIW, this looks good to me.

Not sure what we need to do to fix up the CI, though.

**Comment by jeremycline** [comment]
Ah, you'll need to check in the poetry.lock file as well.

**Comment by mfocko** [comment]
> Ah, you'll need to check in the poetry.lock file as well.

I'll have a look at that, it got lost among the other notifications

**Comment by mfocko** [comment]
Not sure where it's coming from, but I hit this:

```
fedora-messaging % poetry lock
Updating dependencies
Resolving dependencies... (4.8s)

Package docutils (0.21.post1) not found.
````

**Comment by jeremycline** [comment]
I'm not particularly familiar with poetry, but the CI logs said try `poetry lock --no-update` which seems to satisfy the tests locally.

**Comment by mfocko** [comment]
Ah, OK… it works with `--no-update` :facepalm: it was in brackets, so I assumed it's optional

**Pull request merged**
